[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
gate_checker = "dc1WXfU4ZZt9aiskq4WXAm8p38FNWKxQgr9A7K2BkZH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/es/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/*.test.ts"
