[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
gate_checker = "DjEiZonFEZpw4M33ZCpMWnrshPwEJ5ZNmuV8FWQiVWdg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/es/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.spec.ts"
